spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_flyway_db?useUnicode=true&characterEncoding=utf8
    username: root
    password: G1hij2hj@1971
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  flyway:
    baseline-on-migrate: true